version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: pg_database
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgrest:
    image: postgrest/postgrest:latest
    container_name: postgrest_api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://user:password@postgres:5432/mydb
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_SERVER_PORT: 3000

volumes:
  pgdata:
